-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 18:53:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `databasesbuses` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databasesbuses` DEFAULT CHARACTER SET utf8 ;
USE `databasesbuses` ;

-- -----------------------------------------------------
-- Table `mydb`.`Conductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Conductor` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Conductor` (
  `DNI` CHAR(8) Primary key,
  `Nombre` VARCHAR(30) NOT NULL,
  `Teléfono` CHAR(9) NOT NULL,
  `Dirección` VARCHAR(45) NULL,
  `Distrito` VARCHAR(45) NULL,
  `Salario` FLOAT NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL unique
);
-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Provincia` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Provincia` (
  `idProvincia` INT auto_increment PRIMARY KEY,
  `NombreProvincia` VARCHAR(45) NOT NULL
  );
  

-- -----------------------------------------------------
-- Table `mydb`.`Paquetes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Paquetes` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Paquetes` (
  `idPaquetes` CHAR(8) NOT NULL PRIMARY KEY,
  `Descripción` VARCHAR(200) NOT NULL,
  `Peso` FLOAT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Destinatario` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Conductor_DNI` CHAR(8) NOT NULL,
  `Provincia_idProvincia` INT,
  FOREIGN KEY (`Conductor_DNI`) REFERENCES `databasesbuses`.`Conductor` (`DNI`) ON DELETE CASCADE,
  FOREIGN KEY (`Provincia_idProvincia`) REFERENCES `databasesbuses`.`Provincia` (`idProvincia`) ON DELETE CASCADE
  );


-- -----------------------------------------------------
-- Table `mydb`.`Buses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Buses` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Buses` (
  `Matrícula` CHAR(8) NOT NULL,
  `Teléfono para contrato` CHAR(9) NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Capacidad` INT NULL,
  PRIMARY KEY (`Matrícula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conductor_has_Buses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Conductor_has_Buses` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Conductor_has_Buses` (
  `Conductor_DNI` CHAR(8) NOT NULL,
  `Buses_Matrícula` CHAR(8) NOT NULL,
  `fecha` char(10) NOT NULL,
  PRIMARY KEY (`Conductor_DNI`, `Buses_Matrícula`),
  FOREIGN KEY (`Conductor_DNI`)
  REFERENCES `databasesbuses`.`Conductor` (`DNI`) ON DELETE cascade,
  FOREIGN KEY (`Buses_Matrícula`) REFERENCES `databasesbuses`.`Buses` (`Matrícula`) ON DELETE cascade
    );


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
