-- MySQL Script generated by MySQL Workbench
-- Wed Feb 23 18:53:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `databasesbuses` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databasesbuses` DEFAULT CHARACTER SET utf8 ;
USE `databasesbuses` ;

-- -----------------------------------------------------
-- Table `mydb`.`Conductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Conductor` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Conductor` (
  `DNI` CHAR(8) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Teléfono` CHAR(9) NOT NULL,
  `Dirección` VARCHAR(45) NULL,
  `Distrito` VARCHAR(45) NULL,
  `Salario` FLOAT NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Provincia` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Provincia` (
  `idProvincia` CHAR(10) NOT NULL,
  `NombreProvincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paquetes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Paquetes` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Paquetes` (
  `idPaquetes` CHAR(8) NOT NULL,
  `Descripción` VARCHAR(200) NOT NULL,
  `Peso` FLOAT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Destinatario` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Conductor_DNI` CHAR(8) NOT NULL,
  `Provincia_idProvincia` CHAR(10) NOT NULL,
  PRIMARY KEY (`idPaquetes`),
  INDEX `fk_Paquetes_Conductor_idx` (`Conductor_DNI` ASC) VISIBLE,
  INDEX `fk_Paquetes_Provincia1_idx` (`Provincia_idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Paquetes_Conductor`
    FOREIGN KEY (`Conductor_DNI`)
    REFERENCES `databasesbuses`.`Conductor` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paquetes_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `databasesbuses`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Buses` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Buses` (
  `Matrícula` CHAR(8) NOT NULL,
  `Teléfono para contrato` CHAR(9) NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Capacidad` INT NULL,
  PRIMARY KEY (`Matrícula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conductor_has_Buses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `databasesbuses`.`Conductor_has_Buses` ;

CREATE TABLE IF NOT EXISTS `databasesbuses`.`Conductor_has_Buses` (
  `Conductor_DNI` CHAR(8) NOT NULL,
  `Buses_Matrícula` CHAR(8) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`Conductor_DNI`, `Buses_Matrícula`),
  INDEX `fk_Conductor_has_Buses_Buses1_idx` (`Buses_Matrícula` ASC) VISIBLE,
  INDEX `fk_Conductor_has_Buses_Conductor1_idx` (`Conductor_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_Conductor_has_Buses_Conductor1`
    FOREIGN KEY (`Conductor_DNI`)
    REFERENCES `databasesbuses`.`Conductor` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conductor_has_Buses_Buses1`
    FOREIGN KEY (`Buses_Matrícula`)
    REFERENCES `databasesbuses`.`Buses` (`Matrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
